---
title: AFLM Predictions
author: James Day
#date: '2020-08-05'
slug: aflm-predictions
categories:
  - AFLM
tags: []
subtitle: ''
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```
 

```{r prep, include=FALSE}
library(reactable)
library(htmltools)
library(tidyverse)
aflm_finals_sims <- read_rds(here::here("data_files", "raw-data", "AFLM_finals_sims.rds")) 
 
forecasts2 <- aflm_finals_sims$sims_combined %>%
  mutate(
    points = Wins,
    team = Team,
    group = Season,
    spi = elo,
    global_o = elo,
    global_d = elo
  )
home_away_ongoing <- aflm_finals_sims$home_away_ongoing


forecasts2 <- forecasts2 %>%
  mutate(elo.change = ifelse(elo.change == 0, NA, elo.change))

rating_cols <- c("spi", "global_o", "global_d")
group_cols <- c("Wins", "Top.1", "Top.4", "make_finals")
knockout_cols <- c("make_semis", "make_prelim", "make_gf", "win_league")
forecasts2 <- forecasts2[, c(
  "team", "elo", "elo.change", "Form",
  rating_cols,
  group_cols,
  knockout_cols
)]

if(home_away_ongoing) {
  sort_col <- list(Wins = "desc", win_league = "desc")
} else {
  sort_col <- list(win_league = "desc", 
                   make_gf = "desc", 
                   make_prelim = "desc", 
                   make_semis = "desc",
                   Wins = "desc", 
                   elo = "desc")
}
```

```{r functions, include=FALSE}
rating_column <- function(maxWidth = 55, class = NULL, ...) {
  colDef(maxWidth = maxWidth, align = "center", class = paste("cell number", class), ...)
}

group_column <- function(class = NULL, ...) {
  colDef(cell = format_pct, maxWidth = 70, align = "center", class = paste("cell number", class), ...)
}

knockout_column <- function(maxWidth = 70, class = NULL, ...) {
  colDef(
    cell = format_pct,
    maxWidth = maxWidth,
    class = paste("cell number", class),
    style = function(value) {
      # Lighter color for <1%
      if (value < 0.01) {
        list(color = "#aaa")
      } else {
        list(color = "#111", background = knockout_pct_color(value))
      }
    },
    ...
  )
}

format_pct <- function(value) {
  if (value == 0) {
    "  \u2013 "
  } # en dash for 0%
  else if (value == 1) {
    "\u2713"
  } # checkmark for 100%
  else if (value < 0.01) {
    " <1%"
  } else if (value > 0.99) {
    ">99%"
  } else {
    formatC(paste0(round(value * 100), "%"), width = 4)
  }
}

make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}
off_rating_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 1.3)
def_rating_color <- make_color_pal(c("#ff2700", "#f8fcf8", "#44ab43"), bias = 0.6)
knockout_pct_color <- make_color_pal(c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab"), bias = 2)
```

```{r table, include=FALSE}
tbl <- reactable(
  forecasts2,
  pagination = FALSE,
  width = "100%",
  defaultSorted = sort_col,
  #defaultSortOrder = "desc",
  defaultColGroup = colGroup(headerClass = "group-header"),
  columnGroups = list(
    colGroup(name = "Team Rating", columns = rating_cols),
    colGroup(name = "Home and Away Season", columns = group_cols),
    colGroup(name = "Finals Chances", columns = knockout_cols)
  ),
  defaultColDef = colDef(class = "cell", headerClass = "header"),
  columns = list(
    elo = rating_column(
      name = "ELO",
      show = TRUE,
      format = colFormat(digits = 0)
    ),
    elo.change = colDef(
      name = "change",
      show = TRUE,
      maxWidth = 70,
      align = "center",
      format = colFormat(digits = 0),
      cell = function(value) {
        status <- case_when(value > 0 ~ "up", 
                            value < 0 ~ "down",
                            is.na(value) ~ "missing",
                            TRUE ~ "no-change")
        value_text <- case_when(round(value) > 0 ~ paste0("+", round(value)),
                                value > 0 ~ paste0("+", round(value, 1)),
                                round(value) < 0 ~ paste0(round(value)),
                                value < 0 ~ paste0(round(value, 1)),
                                TRUE ~ "-")
        class <- paste0("tag status-", tolower(status))
        htmltools::div(class = class, value_text)
      }
    ),
    team = colDef(
      defaultSortOrder = "asc",
      minWidth = 200,
      headerStyle = list(fontWeight = 700),
      align = "left",
      cell = function(value, index) {
        div(
          class = "team",
          img(class = "flag", alt = paste(value, "flag"), src = paste0("/images/", value, ".svg")),
          div(class = "team-name", value),
          div(class = "record", sprintf("%s", forecasts2[index, "Form"]))
        )
      }
    ),
    group = colDef(
      show = FALSE,
      defaultSortOrder = "asc", align = "center", maxWidth = 75,
      class = "cell group", headerStyle = list(fontWeight = 700)
    ),
    spi = rating_column(
      name = "ELO",
      show = FALSE,
      format = colFormat(digits = 1)
    ),
    Wins = rating_column(
      name = "Proj. Wins",
      class = "border-left",
      cell = function(value) {
        scaled <- (value - min(forecasts2$Wins)) / (max(forecasts2$Wins) - min(forecasts2$Wins))
        color <- off_rating_color(scaled)
        value <- format(round(value, 1), nsmall = 1)
        div(class = "spi-rating", style = list(background = color), value)
      }
    ),
    global_o = colDef(show = FALSE),
    global_d = colDef(show = FALSE),
    Form = colDef(show = FALSE),
    Top.4 = group_column(name = "Top 4"),
    Top.2 = group_column(name = "Top 2"),
    Top.1 = group_column(name = "1st"),
    make_finals = knockout_column(name = "Make Finals"),
    make_semis = knockout_column(name = "Make Semis", maxWidth = 90, class = "border-left"),
    make_prelim = knockout_column(name = "Make Prelim"),
    make_gf = knockout_column(name = "Make GF"),
    win_league = knockout_column(name = "Premier")
  ),
  # Emphasize borders between groups when sorting by group
  rowClass = JS("
    function(rowInfo, state) {
      const firstSorted = state.sorted[0]
      if (firstSorted && firstSorted.id === 'group') {
        const nextRow = state.pageRows[rowInfo.viewIndex + 1]
        if (nextRow && rowInfo.row.group !== nextRow.group) {
          return 'group-last'
        }
      }
    }"),
  showSortIcon = FALSE,
  borderless = TRUE,
  class = "standings-table"
)
```

```{r table_display, echo = FALSE}
rnd <- aflm_finals_sims$sims_combined$Round %>% max()
seas <- aflm_finals_sims$sims_combined$Season %>% max()
time <- lubridate::with_tz(Sys.time(), tzone = "Australia/Melbourne") %>%
  format("%I:%M%p")
date <- lubridate::with_tz(Sys.Date(), tzone = "Australia/Melbourne") %>% 
  format( "%b %d")

div(
  class = "standings",
  div(
    class = "title",
    h2(paste0("AFLM Premiership ", seas, " Season Predictions")),
    "ELO ratings and chances of making various finals for every team in the AFLM competition"
  ),
  paste0("Last updated ", date, " at ", time),
  tbl
)
```

```{r ref.label="table", echo=FALSE}
```


```{r, echo=FALSE}
tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```


```{css, echo =FALSE}
.standings {
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
}
.title {
  margin: 18px 0;
  font-size: 16px;
}
.title h2 {
  font-size: 20px;
  font-weight: 600;
}
.standings-table {
  margin-bottom: 20px;
}
/* Align header text to the bottom */
.header,
.group-header {
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}
.header {
  border-bottom-color: #555;
  font-size: 13px;
  font-weight: 400;
  text-transform: uppercase;
}
/* Highlight headers when sorting */
.header:hover,
.header[aria-sort="ascending"],
.header[aria-sort="descending"] {
  background-color: #eee;
}
.border-left {
  border-left: 2px solid #555;
}
/* Use box-shadow to create row borders that appear behind vertical borders */
.cell {
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
}
.group-last .cell {
  box-shadow: inset 0 -2px 0 #555;
}
.team {
  display: inline-flex;
  align-items: baseline;
  align-content: left;
}
.record {
  margin-left: 5px;
  color: #999;
  font-size: 13px;
}
.team-name {
  font-size: 18px;
  font-weight: 700;
}
.flag {
  margin-right: 8px;
  height: 21px;
  border: 0px solid #f0f0f0;
  align-content: left;
}
.group {
  font-size: 19px;
}
.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 16px;
  line-height: 30px;
  white-space: pre;
}
.spi-rating {
  width: 35px;
  height: 35px;
  border: 1px solid rgba(0, 0, 0, 0.03);
  border-radius: 50%;
  color: #000;
  font-size: 13px;
  letter-spacing: -2px;
  
}

.tag {
  display: inline-block;
  padding: 2px 12px;
  border-radius: 15px;
  font-weight: 600;
  font-size: 12px;
  vertical-align: bottom;
}

.status-up {
  background: rgba(68,171,67,.5);
  color: hsl(116, 30%, 25%);
}

.status-no-change {
  background: hsl(0, 0%, 80%);
  color: hsl(0, 0%, 50%);
}

.status-missing {
  display: none;
}

.status-down {
  background: rgba(255,39,0,.5);
  color: hsl(350, 45%, 30%);
}
```


```{css form-css, echo=FALSE}
# /* rmarkdown html documents */
.container[role="main"] {
  min-width: 100% !important;
  max-width: 1054 !important;
  width: 100%;
}

.container {
  min-width: 100% !important;
  max-width: 1054px !important;
  width: 100%;
}

 #h1.title {
 #  display: none;
 #}
# /* pkgdown articles */
# .contents {
#   width: 1054px;
# }
# .page-header {
#   display: none;
#}
```
