---
title: Current Tips
author: James Day
date: '2018-03-27'
slug: aflm-current-tips
categories:
  - AFLM
  - Predictions
tags: []
---

Welcome to our all new AFL Men's tips page! Here you will the tips for the upcoming rounds. I'll usually aim to update these early in the week to give you time to digest Any questions, let me know on Twitter! 

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

round <-  2

HGA <- 36
B <- 0.025
k_val <- 18
carryOver <- 0.07
M <- 400
```

```{r get data, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# Load libraries
library(fitzRoy)
library(tidyverse)
library(formattable)
library(ggthemes)
library(elo)

# Get fixture data using FitzRoy
fixture <- get_fixture()

# Get results
results <- fitzRoy::get_match_results()
results <- results %>%
  mutate(
    seas_rnd = paste0(Season, ".", Round.Number),
    First.Game = ifelse(Round.Number == 1, TRUE, FALSE)
  )

results_long <- convert_results(results)

# mapping
map_margin_to_outcome <- function(margin, B = 0.025) {
  outcome <- 1 / (1 + (exp(-B * margin)))
  return(outcome)
}

# mapping
map_outcome_to_margin <- function(outcome, B = 0.025) {
  margin <- log((1 / outcome) - 1) / -B
  return(margin)
}

  # calculate ELO
  elo.data <- elo.run(
    map_margin_to_outcome(Home.Points - Away.Points, B = B) ~
    adjust(Home.Team, HGA) +
      Away.Team +
      group(seas_rnd) +
      regress(First.Game, 1500, carryOver) +
      k(k_val * log(abs(Home.Points - Away.Points) + 1)),
    data = results
  )
```


```{r Predictions, echo=FALSE, message=FALSE, warning=FALSE}
# Filter round and do predictions
predictions <- fixture %>%
  mutate(
    Day = format(Date, "%a, %d"),
    Time = format(Date, "%H:%M"),
    Probability = round(predict(elo.data, newdata = fixture), 3),
    Prediction = ceiling(map_outcome_to_margin(Probability)),
    Result = case_when(
           Probability > 0.5 ~ paste(Home.Team, "by", Prediction),
           Probability < 0.5 ~ paste(Away.Team, "by", -Prediction),
           TRUE ~ "Draw"
  )) %>%
  select(Day, Time, Round, Venue, Home.Team, Away.Team, Prediction, Probability, Result)


# Pass those onto Formattable
predictions %>%
  filter(Round == round) %>%
formattable(list(
  Home.Team = formatter("span", style = ~ style("font-weight" = ifelse(Probability >= 0.501, "bold", NA))),
  Away.Team = formatter("span", style = ~ style("font-weight" = ifelse(Probability <= 0.499, "bold", NA)))
  )
  ) 

```
