baseurl = "https://plussixoneblog.com/"
DefaultContentLanguage = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
title = "plusSixOne"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "plussixone"
googleAnalytics = "UA-77406420-1"

[Params]
  subtitle = "Data driven exploration of Australian Sport"
  mainSections = ["post"]
  logo = "img/avator-icon-new.png"
  favicon = "img/favicon-new.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  

[Author]
  name = "James Day"
  website = "plussixoneblog.com"
  email = "jamesthomasday@gmail.com"
  facebook = "plussixoneblog"
  github = "jimmyday12"
  twitter = "plusSixOneblog"
  # reddit = "username"
  linkedin = "james-day-ab648321"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2
    
[[menu.main]]
    name = "Categories"
    url = "categories"
    weight = 3

[[menu.main]]
    identifier = "aflm"
    name = "AFL Mens"
    weight = 4

[[menu.main]]
    parent = "aflm"
    name = "Predictions"
    url = "page/aflm-predictions"
    weight = 1
    
[[menu.main]]
    parent = "aflm"
    name = "Current Tips"
    url = "page/aflm-games"
    weight = 2
    
[[menu.main]]
    parent = "aflm"
    name = "Model Results"
    url = "page/aflm-model-results"
    weight = 3    

[[menu.main]]
    identifier = "aflw"
    name = "AFL Womens"
    weight = 5
    
[[menu.main]]
    parent = "aflw"
    name = "Coming Soon"
    url = "page/aflw-coming-soon/"
    weight = 1


[[menu.main]]
    name = "Cool Links"
    url = "page/cool-links/"
    weight = 6
    



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
