---
title: Simulating the 2018 Season
author: James Day
date: '2018-03-12'
slug: simulating-the-2018-season
categories:
  - AFL
  - Simulation
tags: []
draft: true
---

"Training the house down" is definately not an addage that has applied to me this off-season. Despite the best intentions, I've left it to the final moment to start getting some content for the new season. In fairness, a lot of work behind the scenes has been happening...


```{r setup, include=FALSE}
library(purrr)
library(tidyverse)
library(fitzRoy)
library(plussixelo)

```

```{r get_data, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Download Historical data
results <- get_match_results()

# Process new ELO
historical_data <- process_historical_elo(results)

# Get current ELO
library(dplyr)
current_elo <- historical_data %>% 
  group_by(Team) %>%
  summarise(ELO = last(ELO))


```
```{r get_fixture, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Get Fixture
fixture <- fitzRoy::get_fixture()
```

```{r simulations, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Create simulations - we want to do 10k
sims <- 1:10000

# Start the progress bar
pb <- progress_estimated(length(sims))

# Call map_df to perform all the simulations
sims_df <- sims %>%
  map_df(~{
    pb$tick()$print() # update the progress bar (tick())
    simulate_season(fixture, team_elo = current_elo, simulation = .x) # do function
  })



```


```{r test, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}

# Conmbine with existing

# Summarise wins
# Calculate Rank
# Calculate Percentage of finishing positions
```