---
title: Welcome Back
author: James Day
date: '2018-01-31'
slug: welcome-back
categories:
  - AFL
  - AFL Womens
tags: []
---

Hello! It's been quite a while since there was any content on the site - my last post was before the grand final. However, I have been doing a bit of work behind the scenes as you may notice. I thought I would give a quick update on a few things about the blog and what you can look forward to this year.

<!-- more -->

### Blog migration
As you may have noticed, my blog is looking a little funky. That's because I've recently moved my entire blog from Wordpress over to [Hugo](https://gohugo.io/). This is a static site generator that allows me to use a fantastic R package called [blogdown](https://bookdown.org/yihui/blogdown/) to create and post content. 

I'll spare you the gory details (although I am planning to write a helpful post for anyone interested in doing the same) but the tl:dr version is that I can now write my blogs, run my code, generate my plots and post it all from within R Studio, which is what I was trying to acheive through a bunch of hacks in Wordpress. 

The migration isn't fully complete - there are still some broken links and images and I would like to play around with the theme - but it's close. I'll be working in the coming weeks to get that finalised.

### AFLW
Last year, I was pretty adament that I wanted to do ELO ratings for the AFL Women's competition. While I managed to do this, it was a fair amount of manual work to do since there is no freely available source of AFL women's data. As such, I was manually coding all the games each week before running my ELO calculations. This was a bit of a nightmare and spending that much time collecting data meant that I couldn't actually write any meaningful content. 

Given this constrain, and the fact that I am about to leave the country for 2 weeks, there won't be any content at least over these first few rounds from me. When I get back, I'm going to be busy trying to find a good soure of data so that I don't have to manually create it again. That also brings me to a new project..

### fitzRoy
Those who follow me on [Twitter](https://twitter.com/plusSixOneblog) may have seen a bit of a [cryptic poll](https://twitter.com/plusSixOneblog/status/915901921277362176) a while ago about a new package I was working on with Robert from [anoafl](https://twitter.com/anoafl). Well - we've been making a bit of a progress and hope to release a new package in the coming months that will allow for easy access to many different data sources. We've done the scraping work and so the access of the data will be relatively straightforward, even if you aren't familiar with R. I am hoping that we can get access to some AFL women's data and include it in this package which will give the wider community a great resource to start producing some interesting AFL Women's analytics content! 

We've got a bit of work to do to actually make the package run but keep your ears out. 

That's about it from me - as I said, I'm off overseas on holiday for 2 weeks so you won't get much content from me in that time. I will endevour to get something out when I get back looking at the first few rounds of AFLW and hopefully with some updates about the pacakage! As always, hit me up on [Twitter](https://twitter.com/plusSixOneblog) if you ever want to chat! 


