name: update data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5,8,11,14 * * 4,5,6,0,1"
  push:
    branches:
      - main
      
jobs:
  update-data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install packages
        run: |
          install.packages(c("devtools", "tidyverse", "pacman", "here", "fst", "blogdown", "lubridate", "reactable", "htmltools", "elo", "cli", "tibbletime"))
          devtools::install_github("jimmyday12/fitzRoy", force = TRUE)
        shell: Rscript {0}
      - name: Get data
        run: Rscript -e 'source(here::here("scripts", "weekly_data_process", "weekly_data_process.R"), echo = TRUE)'
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'updating weekly data' || echo "No changes to commit"
          git push || echo "No changes to commit"
