name: Rebuild Site

on:
  push:
    branches:
      - main
      
jobs:
  touch-and-rebuild:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install packages
        run: |
          install.packages(c("devtools", "tidyverse", "pacman", "here", "fst", "blogdown", "lubridate", "reactable", "htmltools"))
          devtools::install_github("jimmyday12/fitzRoy", force = TRUE)
        shell: Rscript {0}
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.66.0")'
      - name: Build site
        run: |
          blogdown:::touch_file(here::here("content", "page", "aflm-predictions.Rmd"))
          blogdown:::touch_file(here::here("content", "page", "aflm-games.Rmd"))
          blogdown:::build_site(TRUE)
        shell: Rscript {0}  
      - name: Commit
        run: |
          git config --global user.name 'James Day'
          git config --global user.email '17557361+jimmyday12@users.noreply.github.com'
          git add .
          git commit -m 'Rebuilding site' || echo "No changes to commit"
          git push || echo "No changes to commit"
