name: Monash Tips

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3"
      
jobs:
  submit-tips:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install packages
        run: |
          install.packages(c("devtools", "tidyverse", "pacman", "here", "monashtipr"))
          devtools::install_github("jimmyday12/fitzRoy", force = TRUE)
        shell: Rscript {0}
      - name: run tips script
        env:
          MONASH_REAL_USER: ${{ secrets.MONASH_REAL_USER }}
          MONASH_REAL_PASS: ${{ secrets.MONASH_REAL_PASS }}
        run: Rscript -e 'source(here::here("scripts", "weekly_monash_tips.R"), echo = TRUE)'
      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updating data"
          git push 
